#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "fathom"
name = "Fathom Lite"
description.en = "Simple, privacy-focused website analytics"
description.fr = "Analyse de site Web simple et respectueuse de la vie privée"

version = "1.3.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://usefathom.com/"
demo = "https://app.usefathom.com/demo"
userdoc = "https://usefathom.com/features/how-fathom-analytics-works"
code = "https://github.com/usefathom/fathom"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir=false
    extract=true
    amd64.url = "https://github.com/usefathom/fathom/releases/download/v1.3.1/fathom_1.3.1_linux_amd64.tar.gz"
    amd64.sha256 = "65a676facaa6fd78e58cd28af304dd719a91460b966f2d58720fd74a9a5c027a"
    arm64.url = "https://github.com/usefathom/fathom/releases/download/v1.3.1/fathom_1.3.1_linux_arm64.tar.gz"
    arm64.sha256 = "b463df056669954ba8d5e41c371a2f6fcf46d67ea176070849e8bcfcedd29875"

    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
